### ISSUE TITLE
Social Committee

### ISSUE THREAD

**Issue by ranti** [code4lib/2021.code4lib.org#181] opened 2021-03-02 23:59 UTC
On https://2021.code4lib.org/schedule/ 
- [x] Game Night: add sign up link 
- [x] Karaoke Night: add sign up link
- [x] Trivia Night: add description
- [x] Trivia Night: add sign up link

On https://2021.code4lib.org/general-info/
- [ ] New "Virtual Quiet Room" page. Draft is being worked on. Wait for Becky's go ahead.

**Comment by dzoladz** [comment] 2021-03-12 16:39
Since I have the links, I'll update the Karaoke and Trivia signups.

**Comment by dzoladz** [comment] 2021-03-12 16:40
I'll also remove the evening 'Community Gathering' card from `peri` mode

**Comment by ranti** [comment] 2021-03-13 08:37
Some changes:
- Information on quiet room will be posted in Whova instead.
- DIY Event Night: this is not really to replace the Community Gathering since it lasts during the whole conference time. 
https://docs.google.com/document/d/13Y1pfFwBoXP5e7TQVwJvCUp3J8w9Q9M2waR7nUFD8Ac/edit?usp=sharing 

To do:
- [x] Remove Community Gatherring subnav and add DIY Event information on https://2021.code4lib.org/general-info/social/

**Comment by dzoladz** [comment] 2021-03-17 23:23
I've removed the 'Community Gathering' from the subnav. If this is finished, feel free to close this issue.

**Comment by dzoladz** [comment] 2021-03-22 11:01
Confirmed the remaining information is in Whova. Closing issue.

**Closed as completed by dzoladz** 2021-03-22 11:01 UTC
